#!/bin/sh

#install sandbox

echo "Cloning Sandbox from Algorand Repository"
git clone https://github.com/algorand/sandbox

cd sandbox

#adding executable permisions to sandbox
chmod u+x sandbox

#starting up sandbox in devnet mode

echo "starting up private devnet network"
./sandbox up dev -v

echo "displaying accounts generated by private network"
echo "note that he accounts have been prefunded"
./sandbox goal account list


echo "alias addresses as ADDR1 ADDR2 and ADDR3"
ADDR1=$(./sandbox goal account list | awk 'FNR==1{ print $2 }')
ADDR2=$(./sandbox goal account list | awk 'FNR==2{ print $2 }')
ADDR3=$(./sandbox goal account list | awk 'FNR==3{ print $2 }')

cd ../

echo "all dependencies installed"
