#!/bin/sh

#install sandbox

echo "Cloning Sandbox from Algorand Repository"
git clone https://github.com/algorand/sandbox

cd sandbox

#adding executable permisions to sandbox
chmod u+x sandbox

#starting up sandbox in devnet mode

echo "starting up private devnet network"
./sandbox up dev -v

echo "displaying accounts generated by private network"
echo "note that he accounts have been prefunded"
./sandbox goal account list


echo "alias addresses as ADDR1 ADDR2 and ADDR3"
ADDR1=$(./sandbox goal account list | awk 'FNR==1{ print $2 }')
ADDR2=$(./sandbox goal account list | awk 'FNR==2{ print $2 }')
ADDR3=$(./sandbox goal account list | awk 'FNR==3{ print $2 }')

cd ../

#install py-algorand-sdk

#create virtual environment and activate it

echo "creating a virtual environment called venv"
python3 -m venv venv

echo "activating the virtual envvironment"
source venv/bin/activate

echo "installing python algorand sdk"
pip3 install py-algorand-sdk

echo "all dependencies installed"
echo "check example-devnet.py for usage"
